### ISSUE TITLE
Insert Crisp into staging and prodcution.

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/www_threefold.tech#29]
Get the new Crips Chat app into: www.threefold.tech and www2.threefold.tech
We won't have a lot of people chatting to us on staging so does not matter to implement it there as well.

html snippet that needs to go into the head:

<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="1a5a5241-91cb-4a41-8323-5ba5ec574da0";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

**Comment by PeterNashaat** [comment]
Done

**Comment by VonSub** [comment]
we had conflicts and now it's dissapeared. could you check again @PeterNashaat

**Comment by PeterNashaat** [comment]
- Fixed
