### ISSUE TITLE
Add Partner content

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/www_threefold.tech#3]
- [x]  Gather content @VonSub
- [x] Create foldout window like team @ehab-hassan (see mockup)

https://invis.io/DFQGT12TES6#/346310438_Artboard

**Comment by VonSub** [comment]
https://invis.io/DFQGT12TES6#/346310438_Artboard

**Comment by ehab-hassan** [comment]
can u send me the foldout content as text so I can copy and past

**Comment by VonSub** [comment]
yes, but there is some difference to what I designed. I would like it to stay inside the "container" just like the team foldouts. If you prepare the .md's i will put in the content myself. But make sure the style is the same as the team foldouts pls.
