### ISSUE TITLE
Add forum to website and add content to it

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/www_threefold.tech#34]
Forum to be added to the website, on categories website. forum.threefold.io has been configured as such so it's redirected correctly. 

# To do
- [ ] Add link on main website
- [ ] Add more links to the related wiki of the (sub-)category
- [ ] Check for adding content: FAQ, ...
- [ ] Check for creating more (sub-)categories, ex. create subcategories in partners&projects? 
- [ ] Refer to the forum on the telegram channel https://t.me/threefoldnetwork/4995

We can get some inspiration from https://forum.holochain.org/

**Comment by VonSub** [comment]
@gmachtel with the sudden go-live i'm getting the button on the website sorted ASAP.
Content will follow soon.

**Comment by VonSub** [comment]
moving to right repo
