### ISSUE TITLE
Apply gradient on background

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/www_threefold.tech#48]
See if you can apply gradient (#00FFFF) to website's background as proposed in mockup:

![TFTAsset 2](https://user-images.githubusercontent.com/20182572/105578752-0e7f6780-5d8b-11eb-81c6-5b38fd570443.png)

**Comment by Vilnite** [comment]
Please make sure background is black (ideally with gradient) permanently. No switch to light mode option.

**Comment by ehab-hassan** [comment]
gradient ll not work there because header section repeated and gradient repeated also and applying it at body ll not match the guide at the top and ll no work fine with responsive ,So I update all to be dark mode all the time,
