### ISSUE TITLE
Update product component

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/www_threefold.tech#53]
- [x] Please remove green background that's currently below title and sub-title
- [x] make sure we can add image that takes the whole square space 

Here we will be using this component for images only, for now.

<img width="1105" alt="Screenshot 2021-02-01 at 14 04 45" src="https://user-images.githubusercontent.com/20182572/106456780-ae797700-6496-11eb-948e-59f65c8ae181.png">

**Comment by Vilnite** [comment]
Please add this product component when updated to farming as well, on Home page above large graph image:

<img width="1163" alt="Screenshot 2021-02-01 at 14 42 21" src="https://user-images.githubusercontent.com/20182572/106460313-d0c1c380-649b-11eb-86ba-e98d9b179c16.png">

**Comment by Vilnite** [comment]
Title and sub-title should come from main.md file:

<img width="1139" alt="Screenshot 2021-02-01 at 17 21 24" src="https://user-images.githubusercontent.com/20182572/106478577-02de2000-64b2-11eb-8d50-2f4804495a25.png">
 
<img width="1287" alt="Screenshot 2021-02-01 at 17 20 56" src="https://user-images.githubusercontent.com/20182572/106478586-05d91080-64b2-11eb-8ecc-014b882acccc.png">

**Comment by Vilnite** [comment]
And we'll need more space after product component:

<img width="1231" alt="Screenshot 2021-02-01 at 17 26 45" src="https://user-images.githubusercontent.com/20182572/106479245-c6f78a80-64b2-11eb-9fdf-7dbb29e64c49.png">

**Comment by ehab-hassan** [comment]
fixed title and subtitle work with markdown now but hided(comment as u did)

**Comment by Vilnite** [comment]
Perfect. Thank you!
