### ISSUE TITLE
TFTECH: Please remove threefold.tech redirect

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/www_threefold.tech#61]
Let's please not point threefold.tech to any other URL. It is OK as threefold.tech.

**Comment by samtaggart** [comment]
@Vilnite @Hamdy Do you have an update here on if we can do this or not?

**Comment by Hamdy** [comment]
we are going to do today

**Comment by samtaggart** [comment]
This looks to be done, I am closing this issue.
