### ISSUE TITLE
Add TF Tech Terms of Use.

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/www_threefold.tech#62]
Add these in the same style as the Privacy statement on the page. DO NOT link to threefold.io wiki's anymore from this page.

[Wiki TERMS OF USE.md](https://github.com/threefoldtech/www_threefold_tech/files/6358586/Wiki.TERMS.OF.USE.md)

**Comment by ehab-hassan** [comment]
done 

![Terms-ThreeFold-Tech](https://user-images.githubusercontent.com/10484295/116208694-75713b80-a741-11eb-9b0a-22624ffc115a.png)
