### ISSUE TITLE
 Terms & Conditions | Privacy Policy Links in the Footer are not redirecting - https://threefold.tech/

### ISSUE THREAD

**Issue by down2basics** [threefoldtech/www_threefold.tech#63]
The Terms & Conditions and Privacy Policy links in the footer of the website are not leading to the actual pages. They just take you back to the top of the main page.

**Comment by Vilnite** [comment]
@hossnys please check if this is the same issue we just had with main website and see how to fix it. Thank you.

**Comment by hossnys** [comment]
@ehab-hassan  will look into it , it's related to site content .

**Comment by ehab-hassan** [comment]
fixed
