### ISSUE TITLE
Urgent tasks to update threefold_tech

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/www_threefold.tech#67]
- [x] Change page title metadata to ThreeFold Tech | Autonomous Computing
- [x] Change header from **Decentralized Cloud Technology** to **A New Era of Autonomous Computing**
- [x] Underneath the header put: ThreeFold Tech is an innovative software technology company that has built a decentralized, autonomous, computing platform. Our unique technology provides unparalleled  sovereignty, scalability and efficiency features that emerging IT workloads require, and that traditional cloud infrastructures cannot deliver. 
- [x] New header graphic: 
![0_1](https://github.com/threefoldfoundation/www_threefold_tech/assets/50134479/fab1e58f-3517-41e4-afd7-1475e441ef70)
- [x] Underneath **The Cyberpandemic Era** put a button that says Learn More with a link to https://info.ourworld.tf/datacenter/cyberpandemic/red/cyber_pandemic.html
- [x] Get rid of everything from here 
![Screen Shot 2023-11-21 at 14 18 09](https://github.com/threefoldfoundation/www_threefold_tech/assets/50134479/60d123be-b5f0-4118-b1d4-cfee4507cbd4)
to here
![Screen Shot 2023-11-21 at 14 18 17](https://github.com/threefoldfoundation/www_threefold_tech/assets/50134479/ea5aa889-bfde-494b-a5dc-cd4fc06a85e4)
- [x] Remove Weynand from "Experience Matters" section

**Comment by samtaggart** [comment]
@ehab-hassan Let's please try these for now and see how it looks

**Comment by samtaggart** [comment]
Keep me posted @samaradel 🙏

**Comment by ehab-hassan** [comment]
@samtaggart ll update staging soon.

**Comment by ehab-hassan** [comment]
@samtaggart https://www2.threefold.tech/ check, please

**Comment by samaradel** [comment]
@samtaggart production updated

**Comment by samtaggart** [comment]
Thank you! Let me confirm with Kristof.

**Comment by samtaggart** [comment]
Let's mark this as closed. No comments yet from KDS.
